version: "3.7"

services:
    pocketbase-clean-template:
        build:
            context: .
            dockerfile: ./compose/local/golang/Dockerfile
        image: pocketbase-clean-template_dev
        container_name: pocketbase-clean-template_dev
        volumes:
            - .:/pocketbase-clean-template:z
        env_file:
            - ./.envs/.local/.golang
        command: /start
        ports:
            - 8080:8080