version: "3.7"

services:
    pocketbase-template:
        build:
            context: .
            dockerfile: ./compose/production/golang/Dockerfile
        image: pocketbase-template
        env_file:
            - ./.envs/.production/.golang
            - ./.envs/.production/.redis
        ports:
            - 8080:8080
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
        volumes:
            - .data:/.data:z

    redis:
        image: redis:alpine
        ports:
            - 6379:6379
        container_name: redis_db

    asynq-monitor:
        image: hibiken/asynqmon 
        container_name: asynq_monitor
        env_file:
            - ./.envs/.production/.redis
            - ./.envs/.production/.asynq
        ports:
            - 8081:8081
        depends_on:
            - redis