version: "3.7"

services:
    pocketbase-clean-template:
        build:
            context: .
            dockerfile: ./compose/production/golang/Dockerfile
        image: pocketbase-clean-template
        env_file:
            - ./.envs/.production/.golang
        ports:
            - 8080:8080
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/ping/"]
        volumes:
            - .data:/.data:z